### ISSUE TITLE
AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/retrocookie#166]
Trying for the first time retrocookie with [a project I have just started](https://github.com/oncleben31/cookiecutter-homeassistant-custom-component). I have the error in the title with the command:
`$ retrocookie ../awesome-custom-component_old`

```console
Traceback (most recent call last):
  File "/Users/benoit/.local/bin/retrocookie", line 8, in <module>
    sys.exit(main())
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/retrocookie/__main__.py", line 116, in main
    retrocookie(
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/retrocookie/core.py", line 145, in retrocookie
    commits = rewrite_commits(
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/retrocookie/core.py", line 65, in rewrite_commits
    RepositoryFilter(
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/retrocookie/filter.py", line 115, in __init__
    self.replacements = get_replacements(
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/retrocookie/filter.py", line 32, in get_replacements
    return [
  File "/Users/benoit/.local/pipx/venvs/retrocookie/lib/python3.8/site-packages/retrocookie/filter.py", line 33, in <listcomp>
    (value.encode(), ref(key).encode())
AttributeError: 'list' object has no attribute 'encode'
```

I expect to backport commits with French strings. So perhaps this is the root cause but I really don't know what type of info I could provide to help to investigate.

**Comment by oncleben31** [comment]
I think I have identified the root cause: 

In my  `.cookiecutter.json`  I use the key `_copy_without_render`:

``` json
{
  "friendly_name": "Awesome custom component",
  "project_name": "{{ cookiecutter.friendly_name | slugify }}",
  "domain_name": "{{ cookiecutter.friendly_name | slugify(separator='_') }}",
  "class_name_prefix": "{{ cookiecutter.domain_name | replace('_', ' ') | title | replace(' ', '') }}",
  "github_user": "oncleben31",
  "version": "0.0.0",
  "_copy_without_render": [
    ".github/workflows/*.yml",
    ".github/workflows/*.yaml"
  ]
}
```

This key is a list and is processed by the [ `get_replacement()` method](https://github.com/cjolowicz/retrocookie/blob/66aac95176a89e93bd11a0c8efefe4f7ed9f683b/src/retrocookie/filter.py#L34) and generate the error.

A quick and dirty fix could be to add the key `_copy_without_render`  to `exclude_variables` . But I see side effects. I think we don't want to replace strings by related token when the commit include a modification in a file identified to not be rendered.

@cjolowicz Do you have ideas on how we should fix it ?

**Comment by cjolowicz** [comment]
Thanks for identifying the issue!

I haven't had time to continue work on this project, so I'll limit myself to a few hopefully helpful comments.

Lists are either choice variables or internal settings, like `_copy_without_render`. In the first case, they would be replaced by a scalar value when rendering `.cookiecutter.json`. In the second case, they will start with an underscore. So a possible fix would be to omit variables that start with an underscore from the reverse replacement, by default. Maybe it makes sense to allow overriding this default via the `--include-variable` option.

Essentially, retrocookie can never hope to be a general solution for backporting changes to project templates, because this problem cannot be solved in generality. That would be like determining a program from its output.

> I think we don't want to replace strings by related token when the commit include a modification in a file identified to not be rendered.

Unfortunately, this one is tricky because we rely on `git --fast-export`, and you cannot easily establish from its format which file or files are associated with a blob.

**Comment by cjolowicz** [comment]
On second thoughts, Cookiecutter passes internal variables to jinja2 like any other variable. Also, values can be both lists and dicts. (I believe even `none` and numbers can end up in the rendered `.cookiecutter.json`.) So maybe the most sensible solution here is to omit anything from the replacements that is not an instance of `str`.

**Comment by cjolowicz** [comment]
On a related note, the cast here is wrong:

https://github.com/cjolowicz/retrocookie/blob/920add9748e981d31586b685468a137be94b896f/src/retrocookie/core.py#L26-L30

**Comment by oncleben31** [comment]
OK I'm working on a fix.
Quick question just after cloning the repository many tests of the nox test session are failing with the message:
```
_pygit2.GitError: reference 'refs/heads/main' not found
```
Any idea where I should look at ?
