### ISSUE TITLE
Missing information in the doc about .cookiecutter.json

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/retrocookie#167]
retrocookie seems to need a `.cookiecutter.json` file to work correctly.

I succeed to reverse engineered what you have done with cookiecutter-hypermodern-python, but I didn't find in any documentation clear explanation how to set the project to generate this file.

It could be great if an experienced user of cookiecutter and retrocookie could add something to help newcomers.

**Comment by cjolowicz** [comment]
True, this should be documented.

The file can be generated by placing it in the template directory, with these contents:

```
{{ cookiecutter | jsonify }}
```

Here is an example: https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/e89a087940d6ef8410adf91385996b097dfd898e/%7B%7Bcookiecutter.project_name%7D%7D/.cookiecutter.json

This uses Cookiecutter's built-in jsonify extension for Jinja. There isn't much in Cookiecutter's documentation about this usage, the original issue is more interesting: https://github.com/cookiecutter/cookiecutter/issues/784
