### ISSUE TITLE
Documentation enhancement thoughts

### ISSUE THREAD

**Issue by Eibwen** [cjolowicz/retrocookie#172]
The readme could use some more clear examples of what happens, and maybe any edgecases you've encountered

Or even just links to a couple repos where you've used it?

This issue is half `TODO to myself` for when I get time to try to set this up for my workflow, update the docs on what I've learned (currently I'm 80% sure this will be very helpful to me, but would like the docs to make it abundantly clear if that is the case or not)

**Comment by cjolowicz** [comment]
Thanks, that's a very good idea!

I added a section with a worked example to the README.rst.

Do you think it makes things clearer for people new to this project?

**Comment by Eibwen** [comment]
I think that looks really good!
